---
title: "RWorksheet_sayson#3a"
author: "Adrian T. Sayson"
date: "2025-10-13"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1.
LETTERS
letters
```
```{r}
#a
first_eleven <- head(LETTERS, 11)
first_eleven
```
```{r}
#b
odd_letters <- LETTERS
odd <- odd_letters[seq(1, length(odd_letters), 2)]
odd
```
```{r}
#c
vowel_letters <- LETTERS
vowels <- vowel_letters [c(1, 5, 9, 15, 21)]
vowels
```
```{r}
#d
last_five <- tail(letters, 5)
last_five
```
```{r}
#e
between <- letters[c(15:24)]
between
```

```{r}
#2a.
#a
city <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban City", "Samal Island", "Davao City")
city
```
```{r}
#b
temp <- c(42, 39, 34, 34, 30, 27)
temp
```
```{r}
#c
weather <- data.frame(city, temp)
weather
```
```{r}
#d
names(weather) <- c("City", "Temperature")
weather
```
```{r}
#e
str(weather)
#The data frame displays the average temperature of the corresponding city. It says that there are 6 objects in each of the 2 variables.
```
```{r}
#f
weather [3, ]
weather [4, ]
```

```{r}
#g
weather[which.max(weather$Temperature), ]
weather[which.min(weather$Temperature), ]
```

```{r}
#2b.
#a
mat <- matrix(data = c(1:8, 11:14),3,4)
mat
```
```{r}
#b
mat * 2
```
```{r}
#c
mat [2, ]
```
```{r}
#d
mat [1:2 ,2:3]
```
```{r}
#e
mat [3, 2:3]
```
```{r}
#f
mat [, 4]
```
```{r}
#g
mat <- matrix(data = c(1:12),3,4)
rownames(mat) <- c("isa", "dalawa", "tatlo")
colnames(mat) <- c("uno", "dos", "tres", "quatro")
print(mat)
```
```{r}
#h
mat <- matrix(data = c(1:8, 11:14),3,4)
dim(mat) <- c(6, 2)
print(mat)
```

```{r}
#3.
array_data <- array(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1))
array_data
```
```{r}
#a
array_data <- array(c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1))
repeated <- rep(array_data, each = 2)
repeated_3d <- array(repeated)
repeated_final <- array(repeated, dim = c(2, 3, 4))
print (repeated_final) 
```
```{r}
#b
print (repeated_final)
# The array has 3 dimensions as seen in "dim" in repeated_final <- array(repeated, dim = c(2, 3, 4)).
```
```{r}
#c
rownames <- letters[1:2]
colnames <- LETTERS[1:3]
dimnames_3d <- c("1st-Dimensional Array", "2nd-Dimensional Array", "3rd-Dimensional Array", "4th-Dimensional Array")
dimnames(repeated_final) <- list(rownames, colnames, dimnames_3d)
print(repeated_final) 
```
