---
title: "Rworksheet_sayson#4"
output:
  pdf_document: default
  html_document: default
---
```{r}
#1.
shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)

height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0,
            74.5, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0,
            64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", 
            "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", 
            "F", "M", "M", "F", "M", "M", "M", "M")
household_data <- data.frame(Shoe_size = shoe_size, Height = height, Gender = gender)

household_data
#a. The dataset contains 28 entries with shoe sizes ranging from 5.0 to 13.0, heights from 59.0 to 77.0 inches, and a mix of male and female individuals.
```
```{r}
#b. 
male_data <- subset(household_data, Gender == "M")
female_data <- subset(household_data, Gender == "F")

male_data
female_data
```
```{r}
#c.
mean(shoe_size)
mean(height)
```
```{r}
#d. Mostly yes, shoe sizes are shown to correlate according to height; the taller they are the bigger the size. However, there are exceptions.
```
```{r}
#2.
months <- c("March","April","January","November","January",
"September","October","September","November","August", "January","November","November","February","May","August", "July","December","August","August","September","November","February",
"April")
factor_months_vector <- factor(months)
factor_months_vector
```
```{r}
#3.
summary(months)
summary(factor_months_vector)
#They are both useful as the summary for months shows the length, class, and mode of the data, while the summary for factor_months_vector shows how many times each month is present.
```
```{r}
#4.
direct <- c("East", "West", "North")
freq <- c(1,4,3)

factor_data <- factor (direct, levels = c("East","West","North"))
print(factor_data)

 table_freq <- data.frame(Direction = factor_data, Frequency = freq)
 print(table_freq)
```
```{r}
#5.
data <- read.table("import_march.csv", header = TRUE, sep = ",")
data
```
```{r}
#6.
user_input_str <- readline(prompt = "Please enter a number between 1 and 50: ")
selected_number <- as.numeric(user_input_str)

if (is.na(selected_number)) {
  cat("Invalid input. Please enter a numerical value.\n")
} else {
  cat("You inputted:", selected_number, "\n")
  
  if (selected_number > 50 || selected_number < 1) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (selected_number == 20) {
    print("TRUE")
  } else {
    cat("The input number is:", selected_number, "\n")
  }
}
```
```{r}
#7.
calculate_min_bills <- function(price_of_snack) {
  denominations <- c(1000, 500, 200, 100, 50)
  
  total_bills <- 0
  
  remaining_amount <- price_of_snack
  
  for (bill in denominations) {
    num_bills_of_this_type <- remaining_amount %/% bill
    
    total_bills <- total_bills + num_bills_of_this_type
    
    remaining_amount <- remaining_amount %% bill
    
    
    if (remaining_amount == 0) {
      break
    }
  }
  
  return(total_bills)
}

set.seed(as.integer(Sys.time()))
possible_prices <- seq(50, 5000, by = 50)
random_price <- sample(possible_prices, 1)

cat("Snack Price:", random_price, "Pesos\n")

min_count <- calculate_min_bills(random_price)

cat("Minimum number of bills needed:", min_count, "\n")
```
```{r}
#8.
#a.
Name <- c("Annie", "Thea", "Steve", "Hanna")
Grade1 <- c(85, 65, 75, 95)
Grade2 <- c(65, 75, 55, 75)
Grade3 <- c(85, 90, 80, 100)
Grade4 <- c(100, 90, 85, 90)

Grades <- data.frame (
  Name,
  Grade1,
  Grade2,
  Grade3,
  Grade4
)
Grades
```
```{r}
#b.
Grades$Average <- (Grades$Grade1 + Grades$Grade2 + Grades$Grade3 + Grades$Grade4) / 4
selected <- Grades[Grades$Average > 90, ]
if(nrow(selected) == 0) {
  cat("No students have an average grade over 90.\n")
} else {
  for(i in 1:nrow(selected)) {
    cat(selected$Name[i], "'s average grade this semester is ", 
        selected$Average[i], ".\n", sep = "")
  }
}
```
```{r}
#c.
test_avgs <- c(
  (Grades$Grade1[1] + Grades$Grade1[2] + Grades$Grade1[3] + Grades$Grade1[4]) / 4,
  (Grades$Grade2[1] + Grades$Grade2[2] + Grades$Grade2[3] + Grades$Grade2[4]) / 4,
  (Grades$Grade3[1] + Grades$Grade3[2] + Grades$Grade3[3] + Grades$Grade3[4]) / 4,
  (Grades$Grade4[1] + Grades$Grade4[2] + Grades$Grade4[3] + Grades$Grade4[4]) / 4
)

# Identify tests with average < 80 and print message
for(i in 1:4) {
  if(test_avgs[i] < 80) {
    cat("The", i, "th test was difficult.\n")
  }
}
```
```{r}
#d.
for(i in 1:nrow(Grades)) {
  g1 <- Grades$Grade1[i]
  g2 <- Grades$Grade2[i]
  g3 <- Grades$Grade3[i]
  g4 <- Grades$Grade4[i]

  highest <- g1
  if(g2 > highest) highest <- g2
  if(g3 > highest) highest <- g3
  if(g4 > highest) highest <- g4

  if(highest > 90) {
    cat(Grades$Name[i], "'s highest grade this semester is ", highest, ".\n", sep = "")
  }
}
```


