---
title: 'Worksheet #2'
author: "Adrian T. Sayson"
date: "2025-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1.
y <- -5:5
y
```

```{r}
#2.
x <- 1:7
x
```

```{r}
#3.
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)
age [3]
age [c(2,4)]
age [-1]
```

```{r}
#4.
z <- c("first"=3, "second"=0, "third"=9)
names(z)

z[c("first", "third")]

# names() in R is a function where only the labels are extracted and not the values of those labels
```

```{r}
#5.
a <- -3:2
a[2] <- 0
a
```

```{r}
#6.
Month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
Price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Purchase_quantity <- c(25, 30, 40, 50, 10, 45)
dataframe <- data.frame (Month, Price_per_liter, Purchase_quantity)
dataframe
             
Fuel <- weighted.mean(x = Price_per_liter, w = Purchase_quantity)
Fuel
```

```{r}
#7.
rivers
elements <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
elements
```

```{r}
#8.
Power <- 1:25
Celebrity <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil Mcgraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
jk <- which(Celebrity == "J.K Rowling")
Power[jk] <- 15
Pay[jk] <- 90
celebrity_df <- data.frame(Power, Celebrity, Pay)
celebrity_df[jk, ]
# The data present is about the influence and rankings of celebrities
```