---
title: 'Worksheet #2'
author: "Adrian T. Sayson"
date: "2025-09-29"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#1.
y <- -5:5
y
#[1] -5 -4 -3 -2 -1  0  1  2  3  4  5
# The output for this code is all numbers from -5 up to 5 in sequential order, shown if printed.

#2.
x <- 1:7
x
#[1] 1 2 3 4 5 6 7

#3.
age <- c(34, 28, 22, 36, 27, 18, 52, 39, 42, 29, 35, 31, 27,
22, 37, 34, 19, 20, 57, 49, 50, 37, 46, 25, 17, 37, 43, 53, 41, 51, 35,
24,33, 41, 53, 40, 18, 44, 38, 41, 48, 27, 39, 19, 30, 61, 54, 58, 26,
18)
age [3]
#[1] 22
age [c(2,4)]
#[1] 28 36
age [-1]
#[1] 28 22 36 27 18 52 39 42 29 35 31 27 22 37 34 19 20 57 49 50 37 46 25 17 37 43 53 41 51 35 24 33 41 53 40 18
#[37] 44 38 41 48 27 39 19 30 61 54 58 26 18

#4.
z <- c("first"=3, "second"=0, "third"=9)
names(z)
#[1] "first"  "second" "third" 
z[c("first", "third")]
#first third 
#    3     9 
# names() in R is a function where only the labels are extracted and not the values of those labels

#5.
a <- -3:2
a[2] <- 0
a
#[1] -3  0 -1  0  1  2
# The second element of the sequence -3 to 2 is replaced by 0

#6.
Month <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun")
Price_per_liter <- c(52.50, 57.25, 60.00, 65.00, 74.25, 54.00)
Purchase_quantity <- c(25, 30, 40, 50, 10, 45)
dataframe <- data.frame (Month, Price_per_liter, Purchase_quantity)
dataframe
#  Month Price_per_liter Purchase_quantity
#1   Jan           52.50                25
#2   Feb           57.25                30
#3   Mar           60.00                40
#4   Apr           65.00                50
#5   May           74.25                10
#6   Jun           54.00                45
Fuel <- weighted.mean(x = Price_per_liter, w = Purchase_quantity)
Fuel
#[1] 59.2625  

#7.
rivers
elements <- c(length(rivers), sum(rivers), mean(rivers), median(rivers), var(rivers),
sd(rivers), min(rivers), max(rivers))
elements
#[1]    141.0000  83357.0000    591.1844    425.0000 243908.4086    493.8708    135.0000   3710.0000

#8.
Power <- 1:25
Celebrity <- c("Tom Cruise", "Rolling Stones", "Oprah Winfrey", "U2", "Tiger Woods", "Steven Spielberg", "Howard Stern", "50 Cent", "Cast of the Sopranos", "Dan Brown", "Bruce Springsteen", "Donald Trump", "Muhammad Ali", "Paul McCartney", "George Lucas", "Elton John", "David Letterman", "Phil Mickelson", "J.K Rowling", "Bradd Pitt", "Peter Jackson", "Dr. Phil Mcgraw", "Jay Lenon", "Celine Dion", "Kobe Bryant")
Pay <- c(67, 90, 225, 110, 90, 332, 302, 41, 52, 88, 55, 44, 55, 40, 233, 34, 40, 47, 75, 25, 39, 45, 32, 40, 31)
jk <- which(Celebrity == "J.K Rowling")
Power[jk] <- 15
Pay[jk] <- 90
celebrity_df <- data.frame(Power, Celebrity, Pay)
celebrity_df[jk, ]
#Power   Celebrity Pay
#19    15 J.K Rowling  90
# The data present is about the influence and rankings of celebrities